/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as MeetingIdRouteImport } from './routes/meeting.$id'
import { Route as MeetingIdIndexRouteImport } from './routes/meeting.$id.index'
import { Route as MeetingIdEditRouteImport } from './routes/meeting.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdRoute = MeetingIdRouteImport.update({
  id: '/meeting/$id',
  path: '/meeting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIdIndexRoute = MeetingIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MeetingIdRoute,
} as any)
const MeetingIdEditRoute = MeetingIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MeetingIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/meeting/$id': typeof MeetingIdRouteWithChildren
  '/meeting/$id/edit': typeof MeetingIdEditRoute
  '/meeting/$id/': typeof MeetingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/meeting/$id/edit': typeof MeetingIdEditRoute
  '/meeting/$id': typeof MeetingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/meeting/$id': typeof MeetingIdRouteWithChildren
  '/meeting/$id/edit': typeof MeetingIdEditRoute
  '/meeting/$id/': typeof MeetingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/new' | '/meeting/$id' | '/meeting/$id/edit' | '/meeting/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/meeting/$id/edit' | '/meeting/$id'
  id:
    | '__root__'
    | '/'
    | '/new'
    | '/meeting/$id'
    | '/meeting/$id/edit'
    | '/meeting/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  MeetingIdRoute: typeof MeetingIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$id': {
      id: '/meeting/$id'
      path: '/meeting/$id'
      fullPath: '/meeting/$id'
      preLoaderRoute: typeof MeetingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$id/': {
      id: '/meeting/$id/'
      path: '/'
      fullPath: '/meeting/$id/'
      preLoaderRoute: typeof MeetingIdIndexRouteImport
      parentRoute: typeof MeetingIdRoute
    }
    '/meeting/$id/edit': {
      id: '/meeting/$id/edit'
      path: '/edit'
      fullPath: '/meeting/$id/edit'
      preLoaderRoute: typeof MeetingIdEditRouteImport
      parentRoute: typeof MeetingIdRoute
    }
  }
}

interface MeetingIdRouteChildren {
  MeetingIdEditRoute: typeof MeetingIdEditRoute
  MeetingIdIndexRoute: typeof MeetingIdIndexRoute
}

const MeetingIdRouteChildren: MeetingIdRouteChildren = {
  MeetingIdEditRoute: MeetingIdEditRoute,
  MeetingIdIndexRoute: MeetingIdIndexRoute,
}

const MeetingIdRouteWithChildren = MeetingIdRoute._addFileChildren(
  MeetingIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  MeetingIdRoute: MeetingIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
